#!/usr/bin/env bash
#
# Wifi Tools is a collection of common tasks for wireless pentesting.

# Import common functions
# source /usr/lib/yojimbosecurity/logging.sh
source ./lib/logging.sh

#######################################
# check_if_root - Check if the user is root
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   None
# Outputs:
#   None
#######################################
check_if_root() {
    if [[ $EUID -ne 0 ]]; then
        log::err "This script must be run as root" 1>&2
        exit 1
    fi
}

#######################################
# main - Main function
# Globals:
#   None
# Arguments:
#   $@ - Command line arguments
# Returns:
#   None
# Outputs:
#   None
#######################################
main() {
    check_if_root
    log::info "Hello World"
}

main "$@"